# generated by datamodel-codegen:
#   filename:  example.json
#   timestamp: 2024-03-03T20:19:08+00:00

from __future__ import annotations

from pydantic import BaseModel


class EmergencyContact(BaseModel):
    name: str


class StudentForm(BaseModel):
    name: str
    description: str
    grade: None
    emergency_contact: EmergencyContact


class Model(BaseModel):
    student_form: StudentForm
